apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bilibili_tool.fullname" . }}
  labels:
    {{- include "bilibili_tool.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bilibili_tool.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bilibili_tool.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.volumes.enabled }}
      volumes:
      - name: {{ .Values.volumes.name }}
        hostPath: 
          path: {{ .Values.volumes.path }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- if .Values.volumes.enabled }}
          volumeMounts:
          - mountPath: "/bilibili_tool/Logs"
            name: {{ .Values.volumes.name }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
